# Generated by Django 5.2.5 on 2026-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestworkflowstep',
            name='action',
            field=models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('reassignment', 'Reassignment'), ('comment', 'Comment'), ('reraise', 'Re-raise')], max_length=20),
        ),
    ]
